### ISSUE TITLE
Could you include checking "rel" tag on <a> tag?

### ISSUE THREAD

**Issue by alexgarciab** [rvalitov/backlink-checker#3]
I use this script almost every week to check if my backlinks are live. One good thing to include when running the script would be a parameter (true or false), to check the rel tag of the links. Apart from knowing if the link is found in the page, it would be useful to know what type of link it is. Because not all the links pass linkjuice:

- dofollow
- nofollow
- sponsored
- ugc

For reference: https://support.google.com/webmasters/answer/96569

If nothing is inside the rel tag or if there is no rel tag, the default value would be "dofollow".

**Comment by rvalitov** [comment]
Yes, I think that's possible. At least for cases when there's only a single value inside the `rel` attribute.

**Comment by alexgarciab** [comment]
Hey @rvalitov - Would you be able to do that finally?

**Comment by rvalitov** [comment]
Sorry, currently I'm not able to implement this. I will leave this issue opened, and come back later to it, but I have no ETA here.
