### ISSUE TITLE
Not detecting links with HTML styling inside

### ISSUE THREAD

**Issue by alexgarciab** [rvalitov/backlink-checker#5]
Hey Ramil, here is another improvement for the backlink checker script to make it even better. I think this is a quick fix and it will help with false positives that currently happen right now.

So I have these type of links:

`<a href="https://website.com"><span style="font-weight: 400;">in this website</span></a>`
`<a href="https://example.com"><strong>https://example.com</strong></a>`

These links currently don't get detected, and they are marked as if they are not in the website. I guess the problem is related with the HTML/CSS styling they have inside the <a> tag.

**Comment by rvalitov** [comment]
Sorry, currently I'm not able to implement this. I will leave this issue opened, and come back later to it, but I have no ETA here.
